// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVRew2JP754f1-MftFIyMunIMtlj3CzdQ',
    appId: '1:1006717159296:web:268be9aa7e5977c448e365',
    messagingSenderId: '1006717159296',
    projectId: 'e-20-21d65',
    authDomain: 'e-20-21d65.firebaseapp.com',
    storageBucket: 'e-20-21d65.appspot.com',
    measurementId: 'G-W1HRVL3H0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp8wXoagAVb11tltpcjaf1jjZyU6GwH6Y',
    appId: '1:1006717159296:android:cd894b595a9e1fde48e365',
    messagingSenderId: '1006717159296',
    projectId: 'e-20-21d65',
    storageBucket: 'e-20-21d65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh9o3q3ZwYx-6d83gb1yx1ytET6rZQmjk',
    appId: '1:1006717159296:ios:860412d2158432f548e365',
    messagingSenderId: '1006717159296',
    projectId: 'e-20-21d65',
    storageBucket: 'e-20-21d65.appspot.com',
    iosBundleId: 'com.example.e20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh9o3q3ZwYx-6d83gb1yx1ytET6rZQmjk',
    appId: '1:1006717159296:ios:d03251e57dcee6b248e365',
    messagingSenderId: '1006717159296',
    projectId: 'e-20-21d65',
    storageBucket: 'e-20-21d65.appspot.com',
    iosBundleId: 'com.example.e20.RunnerTests',
  );
}
